services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-local-chat-ng
    ports:
      - "4201:4201"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
